version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: timeformed_postgres
    environment:
      POSTGRES_DB: timeformedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "6969:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
