server:
  address: 0.0.0.0

spring:
  application:
    name: timeformed

  datasource:
    url: jdbc:postgresql://localhost:6969/timeformedb
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
