server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: timeformed

  datasource:
    # En Docker usará SPRING_DATASOURCE_URL (Compose); en local cae al default:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6969/timeformedb}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
